#grpc:
#  server:
#    port: 9090


spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: 1234
    pool:
      enabled: true
#      initial-size: 10
#      max-size: 50
  netty:
    leak-detection:
      level: paranoid
    allocator: pooled

grpc:
  enable-reflection: true
  port: 9090
