version: "3"
services:
  redis-server:
    image: "redis"
    expose:
      - 6379
  node-app:
    depends_on:
      - redis-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
