// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/com/binghe/proto/object.proto
// Protobuf Java Version: 4.28.2

package com.binghe.proto;

public interface LargeObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LargeObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .SmallObject smallObjects = 3;</code>
   */
  java.util.List<com.binghe.proto.SmallObject> 
      getSmallObjectsList();
  /**
   * <code>repeated .SmallObject smallObjects = 3;</code>
   */
  com.binghe.proto.SmallObject getSmallObjects(int index);
  /**
   * <code>repeated .SmallObject smallObjects = 3;</code>
   */
  int getSmallObjectsCount();
  /**
   * <code>repeated .SmallObject smallObjects = 3;</code>
   */
  java.util.List<? extends com.binghe.proto.SmallObjectOrBuilder> 
      getSmallObjectsOrBuilderList();
  /**
   * <code>repeated .SmallObject smallObjects = 3;</code>
   */
  com.binghe.proto.SmallObjectOrBuilder getSmallObjectsOrBuilder(
      int index);
}
